name: "EKS_Deployment"

on:
  push:
    branches:
      - main
      - staging
    paths:
      - eks-cluster/**
  pull_request:
    branches:
      - main
    paths:
      - eks-cluster/**
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: vprofile-eks

jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./eks-cluster
    steps:
      - uses: actions/checkout@v4
      - uses: snyk/actions/setup@master
      - uses: actions/setup-go@v1
        with:
          go-version: '1.13'
      - name: Snyk monitor
        run: snyk iac test --report
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  terraform:
    needs: security
    name: "Apply Terraform Code changes"
    uses: Amits64/shared_library/.github/workflows/terraform-setup.yml@main
    with:
      aws-region: ${{ env.AWS_REGION }}
      tf-cloud-token: ${{ secrets.TF_CLOUD_TOKEN }}
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      working-directory: "./eks-cluster"

  configure_kube:
    needs: terraform
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./eks-cluster
    steps:
      - name: "Get Kube config file"
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}
        
      - name: "Install Ingress Controller"
        run: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
