name: EKS Deployment

on:
  push:
    branches:
      - main
      - staging
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: Amits64/shared_library/.github/workflows/terraform-setup.yml@main
    with:
      aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
      aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      aws-region: ${{ secrets.AWS_REGION }}
      tf-cloud-token: ${{ secrets.TF_CLOUD_TOKEN }}
      working-directory: "./eks-cluster"

    steps:
      - name: "Get Kube config file"
        id: getconfig
        if: ${{ job.status == 'success' }}
        run: aws eks update-kubeconfig --region ${{ secrets.AWS_REGION }} --name ${{ secrets.EKS_CLUSTER }}

      - name: "Install Ingress Controller"
        if: ${{ job.status == 'success' && steps.getconfig.outcome == 'success' }}
        run: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
