name: "EKS_Deployment"

on:
  push:
    branches:
      - main
      - staging
    paths:
      - eks-cluster/**
  pull_request:
    branches:
      - main
    paths:
      - eks-cluster/**
  workflow_dispatch:

env:
  AWS_REGION: us-east-1
  EKS_CLUSTER: vprofile-eks

jobs:
  security:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./eks-cluster
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4
      
      - name: Set up Snyk
        uses: snyk/actions/setup@master

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.13'
          
      - name: Snyk monitor
        run: snyk iac test --report
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  terraform:
    needs: security
    name: "Apply Terraform Code changes"
    runs-on: ubuntu-latest

    steps:
      - name: Call Terraform Setup
        uses: org/org-workflows/.github/workflows/terraform-setup.yml
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
          tf-cloud-token: ${{ secrets.TF_CLOUD_TOKEN }}
          working-directory: ./eks-cluster

      - name: Get Kube config file
        if: steps.apply.outcome == 'success'
        run: aws eks update-kubeconfig --region ${{ env.AWS_REGION }} --name ${{ env.EKS_CLUSTER }}

      - name: Install Ingress Controller
        if: steps.apply.outcome == 'success'
        run: kubectl apply -f https://raw.githubusercontent.com/projectcalico/calico/v3.25.0/manifests/calico.yaml
