name: "EKS_Destroy"

on:
  workflow_dispatch:

jobs:
  destroy_eks:
    runs-on: ubuntu-latest
    name: Terraform destroy
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Terraform
      uses: hashicorp/setup-terraform@v1
      with:
        terraform_version: 1.9.3

    - name: "Configure Terraform credentials"
      run: |
        mkdir -p ~/.terraform.d
        cat > ~/.terraform.d/credentials.tfrc.json <<EOF
        {
          "credentials": {
            "app.terraform.io": {
              "token": "${{ secrets.TF_CLOUD_TOKEN }}"
            }
          }
        }
        EOF

    - name: Terraform init with remote backend
      working-directory: ./eks-cluster
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init -backend-config="hostname=app.terraform.io" -backend-config="organization=SFBTraining"

    - name: Migrate state to remote backend
      working-directory: ./eks-cluster
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform init -migrate-state

    - name: Terraform destroy
      working-directory: ./eks-cluster
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      run: terraform destroy -auto-approve
